---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: color
  namespace: default
spec:
  encryptedData:
    COLOR_ENV: AgB1W028jB2rRpCVFxJThO+bVl9rQ0Vtp8UMSBgQXzckZf1aLiTjR+qhFhW0nPQOw7hrkMmSTYPFukm0DUN4T5tmV8MGMOFYGnqGCynFzDiveEmvUZL8sz/RercAzYwR2PoDNwIlNX5gg170axzz7IsfFVhyWf4aekQ8z6U7UUJt5m40+U3IWl9urzl6Cw0XBypVIvolfgBujL+fvwGaj4w1j/ydcm+g2Whb7cIgzZKRrmsm9+LFzJl3DJ2bJL6g0vV5tUmZOROfUwuivYT3W7o22N5N6CfF5VnxCaOQLWNp8xf2e5xw5JdwxRBrxNsDyaG/cYPLSBcysssLE3BHFwcLH6HYg/Sv8Tyg8gd48ysbsbmRFOwuyDooXqofMxYGnAA0aq0Tf56HWomEx+vd28EJKAr2aJ6ksrS/K+/tPWghuKxU8TVuApTfdQTr1HHa4EyFO+y/v+sPia6XDF46eDjA/UIrGJJQoZXHUbYildq7yiGHcUrjNid0YhSQTryS2CjP8KnKzXdvMXgcPDVvH9mfHthGcPY9uk6U1qprpMZjmDKCSD7JDLsTyxOIDY/wR/7HV/WtKSVZNG1fY7ghLHw9f6OmNUpDcm3KFoUpKcysP0aAMZoQOfkCP5aLYr0idgfZAow3JtxnIlLOhrMQjffcQsn0vngiQUWik6I5UIHaVffUtD5FNrUiwZnk0QBtqg8BiDs=
  template:
    metadata:
      creationTimestamp: null
      name: color
      namespace: default
